service: nookwill

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2

package:
 include:
   - backend/handler.js
 exclude:
   - tf/**
   - .gitignore

functions:
 
          